app/models.py
from . import db
from werkzeug.security import generate_password_hash,check_password_hash
from flask_login import UserMixin
from . import login_manager
from datetime import datetime

@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))
    

class User(db.Model, UserMixin):
    __tablename__ ='users'

    id=db.Column(db.Integer, primary_key=True)
    username=db.Column(db.String(255))
    email=db.Column(db.String(255), unique=True, index = True)
    bio=db.Column(db.String(255))
    # profile_pic_path=db.Column(db.String())
    password_hash=db.Column(db.String(255))
    pass_secure = db.Column(db.String(255), unique=True, index=True)
    pitch = db.relationship('Pitch',backref = 'user',lazy = "dynamic")
    comment = db.relationship('Comment',backref='user',lazy = "dynamic")

    @property
    def password(self):
        raise AttributeError('You cannot read the password attribute')

    @password.setter
    def password(self, password):
        self.pass_secure = generate_password_hash(password)


    def verify_password(self,password):
        return check_password_hash(self.pass_secure,password)


    def __repr__(self):
        return f'User {self.username}'

class Pitch(db.Model):
    __tablename__='pitches'

    id=db.Column(db.Integer, primary_key=True)
    pitch_title=db.Column(db.String)
    pitch_id=db.Column(db.Integer)
    pitch_idea=db.Column(db.String(1000))
    category=db.Column(db.String(255))
    posted=db.Column(db.DateTime, default=datetime.utcnow)
    user_id=db.Column(db.Integer, db.ForeignKey("users.id"))
    comment = db.relationship('Comment', backref='pitch', lazy='dynamic')

# class Pitch:
#     def __init__(self, pitch_title, pitch_idea, category ):
#         self.pitch_title = pitch_title
#         self.pitch_idea = pitch_idea


    def save_pitch(self):
        db.session.add(self)
        db.session.commit()

    @classmethod 
    def get_pitches(cls,id):
        pitches=Pitch.query.filter_by(pitch_id=id).all()
        return pitches


class Comment(db.Model):
       __tablename__='comments'

       id=db.Column(db.Integer, primary_key=True)
       comment=db.Column(db.String(1000))
       user_id= db.Column(db.Integer,db.ForeignKey('users.id'))
       pitch_id= db.Column(db.Integer,db.ForeignKey('pitches.id'))

       def save_comment(self):
            db.session.add(self)
            db.session.commit()
        
       @classmethod
       def get_comment(cls,pitch_id):
            comment = Comment.query.filter_by(pitch_id=pitch_id).all()
            return comment

       def _repr_(self):
            return f'Comment: {self.comment}'

app/main/forms.py
from wtforms import StringField,TextAreaField, SubmitField, SelectField
from wtforms.validators import Required
from flask_wtf import FlaskForm

class UpdateProfile(FlaskForm):
    bio = TextAreaField('Update details about you here',validators = [Required()])
    submit = SubmitField('Submit')


class PitchForm(FlaskForm):

 pitch_title = StringField('Pitch Title',validators=[Required()])

 pitch_idea = TextAreaField('Pitch Idea')
 
 category = SelectField('Category', choices=[('PROGRAMMING','PROGRAMMING'), ('BUSINESS','BUSINESS'),('LOVE','LOVE')], validators=[Required()])

 submit = SubmitField('Submit')

class CommentsForm(FlaskForm):
    comment = TextAreaField(' Comment section')
    submit = SubmitField('Comment')

app/__init__.py
from flask import Flask
from config import config_options
from flask_bootstrap import Bootstrap
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager
# from flask_uploads import UploadSet, configure_uploads, IMAGES
from flask_mail import Mail


db=SQLAlchemy()
bootstrap=Bootstrap()
mail=Mail()

login_manager=LoginManager()
login_manager.session_protectio='strong'
login_manager.login_view='auth.login'
# photos=UploadSet('photos',IMAGES)



def create_app(config_name):
    app=Flask(__name__)
    app.config.from_object(config_options[config_name])
    bootstrap.init_app(app)
    db.init_app(app)
    login_manager.init_app(app)
  

    from .auth import auth as auth_blueprint
    app.register_blueprint(auth_blueprint,url_prefix = '/authenticate')

    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)

    # from .requests import configure_request
    # configure_request(app)
    mail.init_app(app)
    # configure_uploads(app,photos)
    return app

app/main/__init__.py
from flask import Blueprint
main = Blueprint('main',__name__)
from . import views,errors

app/main/views.py
from flask import render_template,request, redirect, url_for,abort
from . import main
from ..models import Pitch, User, Comment
from .. import db
from flask_login import login_required,current_user
from .forms import UpdateProfile, PitchForm, CommentsForm

@main.route('/')
def index():
    return render_template('index.html')

@main.route('/user/<uname>')
def profile(uname):
    user=User.query.filter_by(username=uname).first()

    if user is None:
        abort(404)
    return render_template('profile/profile.html',user=user)

@main.route('/user/<uname>/update',methods = ['GET','POST'])
@login_required
def update_profile(uname):
    user = User.query.filter_by(username = uname).first()
    if user is None:
        abort(404)

    form = UpdateProfile()

    if form.validate_on_submit():
        user.bio = form.bio.data

        db.session.add(user)
        db.session.commit()

        return redirect(url_for('.profile',uname=user.username))

    return render_template('profile/update.html',form =form)

@main.route('/newpitch', methods = ['POST', 'GET'])
@login_required
def new_pitch():
    form = PitchForm()
    
    if form.validate_on_submit():
        pitch_title = form.pitch_title.data
        category = form.category.data
        pitch_idea = form.pitch_idea.data
        new_pitch = Pitch(pitch_title=pitch_title,category=category,pitch_idea=pitch_idea,user=current_user)

        new_pitch.save_pitch()
        db.session.add(new_pitch)
        db.session.commit()

        return redirect(url_for('main.single_pitch' ))
    else:
        all_pitches = Pitch.query.order_by(Pitch.posted).all()

  
    return render_template('newpitch.html',pitches=all_pitches, pitch_form=form)

@main.route('/pitches', methods=['POST','GET']) 
@login_required
def single_pitch():
    """get single  pitch"""
   
    commentform= CommentsForm()
    if commentform.validate_on_submit():
            new_comment= commentform.comment.data
            user_id = current_user._get_current_object().id
            # pitch_id = current_user._get_current_object().id
            #pitch_id=Pitches.query.get(Pitches.id)
            new_comment= Comment(comment=new_comment,user_id=user_id)
            new_comment.save_comment()
            db.session.add(new_comment)
            db.session.commit()
            return redirect(url_for('main.single_pitch'))
    else:

            all_pitches = Pitch.query.order_by(Pitch.posted).all()
            comments=Comment.query.order_by(Comment.comment).all()
        
    
    return render_template('pitches.html', pitches=all_pitches, comments=comments, commentform=commentform)

# @main.route('/user/<uname>/update/pic',methods= ['POST'])
# @login_required
# def update_pic(uname):
#     user = User.query.filter_by(username = uname).first()
#     if 'photo' in request.files:
#         filename = photos.save(request.files['photo'])
#         path = f'photos/{filename}'
#         user.profile_pic_path = path
#         db.session.commit()
#     return redirect(url_for('main.profile',uname=uname))

app/templates/base.html
{% extends 'bootstrap/base.html'%}


{% block navbar %}
    {% include 'navbar.html' %}
{% endblock %}

app/templates/index.html
{%  extends "base.html"%}
{% block content %}

<div class='overall'>
<h3> <marquee>Welcome Pitching website.You have an idea, this is a perfect site for you. Sign up and continue</marquee></h3>
<div></div>
<div class="container" style="display:flex; background-color: aqua; margin-top:0px ">
    <div class="card" style="margin:30px">
<div class="card-body"><a class="btn btn-primary" href="/newpitch">New Pitch</a></div> 
<br>
</div>
<div class="card " style="margin:30px">
  
<div class="card-body"><a class="btn btn-primary" href="/pitches">View Pitches</a></div>
</div>
</div>
{% endblock %}

app/templates/navbar.html
<div class="navbar navbar-inverse" role="navigation">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/"> Ideas Pitching website </a>
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li><a href="/">Home</a></li>
        </div>
        <ul class="nav navbar-nav navbar-right">
          {% if current_user.is_authenticated %}
          <li><a href="{{url_for('main.profile',uname=current_user.username)}}">Profile</a></li>
          <li><a href="{{url_for('auth.logout')}}">Sign out</a></li>
          {% else %}
          <li><a href="{{url_for('auth.login')}}"><button class="btn btn-success">Sign in</button></a></li>
          <li><a href="{{url_for('auth.register')}}"> <button class="btn btn-success">Sign  up</button> </a></li>
          {%endif%}
        </ul>
        
        
    </div>
</div>

app/templates/newpitch.html
{% extends 'base.html'%}
{% import 'bootstrap/wtf.html' as wtf%}
{% block content %}
<div class="container">

    <h3>Make a new pitch</h3>
    <!-- new pitch form goes here -->

  <div class="row">
      <div class="col-sm">
        <div class="card card-body">
            <h4>New pitch</h4>
            <div>
                {{wtf.quick_form(pitch_form)}}
            </div>
   
    
        </div>
      </div>
  </div>
</div>

{%endblock%}

app/templates/pitches.html
{%extends 'base.html'%}
{%block content %}
{% import 'bootstrap/wtf.html' as wtf%}

{%block styles %}
{{super()}}
<link rel="stylesheet" href="{{url_for('static', filename= 'css/styles.css')}}">
{%endblock %}

<div class="container">
    <div class="card">
        <nav class="navbar navbar-light bg-light">
            <form class="form-inline">
              <a class="btn btn-info" type="button" href="/newpitch">Create new pitch</a>
              
            </form>
          </nav>
        <h3>Welcome , view pitches here</h3>
        <div class="card">
            <ul type=none>
                {% for pitch in pitches%}
                <div class="card-body bg-secondary">
                    <li>
                        <h3>{{pitch.title}}</h3>
                    </li>
                    <h6><b>Category: </b>{{pitch.category}}</h6>
                    <p><b>idea: </b>{{pitch.pitch_idea}}</p>
                    <p> <b>posted at:</b> <em>{{pitch.posted}}</em></p>
                    <b>Comments: </b>
                 <ul>
                    {%for comment in comments %}
                    <li>
                        {{comment.comment}}
                    </li>
                    {%endfor %}
                 </ul>

                    {{wtf.quick_form(commentform)}}
                    <hr>

                </div>
                {% endfor %}
            </ul>


        </div>
    </div>
    {% endblock %}

app/templates/profile/profile.html
{% extends 'base.html'%}

{% block content %}
<div class="container">
<div class="row">
<!-- displaying  Username-->
  <div class="col-md-4">
    <h3> {{user.username| capitalize}} </h3>

    <!--Displaying user bio-->
    {% if user.bio %}
      <p> {{user.bio}}</p>
    {%else%}
      <p> {{user.username| capitalize}} has no bio </p>
    {% endif %}
    {% if user == current_user %}
    <a href="{{url_for('main.update_profile',uname=user.username)}}">Edit profile</a>
{% endif %}
  </div>

  <!--Display profile photo-->
  <div class="col-md-4">

    {% if user.profile_pic_path %}
    <img src="{{url_for('static',filename=user.profile_pic_path)}}" alt="" class="img-thumbnail">
    {%else%}
    <p>No profile picture</p>
    {% endif %}
  </div>

</div>
</div>
</div>
{% endblock %}

app/templates/profile/update.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block content %}
<div class="container">
  {{wtf.quick_form(form)}}
</div>
{% endblock %}